[libosmium]
git-tree-sha1 = "d3f005375c1558be882c1c4c2c42f6b72953a723"

    [[libosmium.download]]
    sha256 = "6a90d9ea6f93a2fb7a3de404974f5b5ecc2b4ceed77d3bf37d75cbfed798bcd5"
    url = "https://github.com/JuliaBinaryWrappers/libosmium_jll.jl/releases/download/libosmium-v2.19.0+0/libosmium.v2.19.0.any.tar.gz"
